export const GET_BOOKS = 'GET_BOOKS'
export const GET_BOOK  = 'GET_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const DELETE_CHAPTER = 'DELETE_CHAPTER'
export const GET_CHAPTER = 'GET_CHAPTER'
export const GET_TOPICS = 'GET_TOPICS'
